"""empty message

Revision ID: 087e6692abda
Revises: 9102dc3c746b
Create Date: 2023-12-27 21:52:47.564647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087e6692abda'
down_revision = '9102dc3c746b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('crew_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('crew_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
