"""empty message

Revision ID: d9fff498b235
Revises: 087e6692abda
Create Date: 2023-12-28 19:48:16.098006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9fff498b235'
down_revision = '087e6692abda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starcoins', sa.Integer(), nullable=False))
        batch_op.drop_column('power')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power', sa.INTEGER(), nullable=False))
        batch_op.drop_column('starcoins')

    # ### end Alembic commands ###
